        *      597   sound/soc/codecs/wm8987.c
        *      597   sound/soc/codecs/alc5621.c
M       *      597   sound/soc/codecs/es8328.c
M       *      597   sound/soc/imapx200/imapx200-i2s.c
M              597   sound/soc/imapx200/imapx200_es8328.c
        *      597   arch/arm/plat-imap/include/plat/devs.h
        *      597   arch/arm/plat-imap/pm_imapx200.c
        *      597   arch/arm/mach-imapx200/configs/hdmi_config
        *     1284   arch/arm/mach-imapx200/configs/lcd_config
        *     1284   arch/arm/mach-imapx200/configs/touchscreen_config
        *      597   arch/arm/mach-imapx200/configs/acc_config
        *      597   arch/arm/mach-imapx200/devices.c
        *      597   arch/arm/mach-imapx200/cpu.c
        *     1284   arch/arm/configs/wwe10_defconfig
        *     1284   arch/arm/configs/m702sa_defconfig
        *     1284   arch/arm/configs/m799ca_defconfig
        *     1284   arch/arm/configs/m799sa_defconfig
        *     1284   arch/arm/configs
M       *      597   init/main.c
M       *      597   drivers/mtd/nand/imapx200.c
M       *      597   drivers/input/serio/ambakmi.c
M              597   drivers/input/serio/serio.c
        *      597   drivers/input/touchscreen/Makefile
M              597   drivers/input/touchscreen/ads7846.c
M              597   drivers/input/touchscreen/tsc2007.c
        *      597   drivers/input/touchscreen
        *      597   drivers/input/keyboard/Makefile
        *      597   drivers/input/keyboard/Kconfig
M              597   drivers/input/keyboard/imapx200_gpio_keys.c
M              597   drivers/input/keyboard/atkbd.c
M              597   drivers/soops/soops.c
M       *      597   drivers/soops/soops.h
M             1284   drivers/video/hdmi/chips/ep932m/EP932Controller.c
M       *      788   drivers/video/hdmi/chips/ep932m/EP932_If.c
A  +  C          -   drivers/video/hdmi/chips/ep932m/imap_HDMI.c
      >   local edit, incoming delete upon update
!             1284   drivers/video/hdmi/chips/ep932m
!       *     1284   drivers/video/hdmi/chips
        *      788   drivers/video/hdmi/Makefile
        *     1284   drivers/video/hdmi/hdmi.c
        *      788   drivers/video/hdmi/hdmi.h
!             1284   drivers/video/hdmi
M              597   drivers/video/infotm/lcds/lcd_9127050000a.c
        *      597   drivers/video/infotm/lcds/Makefile
M              597   drivers/video/infotm/lcds/lcd_AT102TN42.c
        *      597   drivers/video/infotm/lcds
        *      597   drivers/video/infotm/logos
M       *     1450   drivers/video/infotm/imapfb.c
M             1976   drivers/video/backlight/imapx200_bl.c
M              944   drivers/video/backlight/Makefile
        *      597   drivers/video/logo/Kconfig
!             1284   drivers/video
M       *      597   drivers/power/android_fake_battery.c
        *      597   drivers/power
M              597   drivers/hid/hid-core.c
M       *      597   drivers/hid/hid-input.c
        *      597   drivers/char/vt_ioctl.c
M              597   drivers/net/gmac-univ_ethernet/gmac-univ_ethernet.c
        *      788   drivers/memalloc
M       *     1284   drivers/usb/serial/option.c
M       *      788   drivers/usb/gadget/ix200_udc.c
        *     1274   drivers/usb/storage/unusual_devs.h
        *      597   drivers/i2c/chips/Makefile
        *      597   drivers/i2c/chips
        *      597   drivers/i2c/busses/i2c1-imapx200.c
M       *      597   drivers/i2c/busses/i2c0-imapx200.c
M              816   drivers/switch/switch_wifi.c
M              597   drivers/spi/spi_imapx200.c
M             1274   drivers/mmc/core/sdio.c
M             1274   drivers/mmc/host/sdhci-imap.c
!             1284   drivers
M             1284   Makefile
M              597   include/linux/spi/ads7846.h
!             1284   .
Status against revision:   2600
